print ("Roses are {colour}")
print ("{plural noun} are blue")
print ("I love {celebrity}")
colour = input("Enter a colour:")
plural_noun = input("Enter a plural noun:")
celebrity = input("Enter a plural noun:")
print ("Roses are"+ colour)
print (plural_noun + "are blue")
print ("I love" + celebrity)